### ISSUE TITLE
MongoError: topology was destroyed

### ISSUE THREAD

**Issue by knolleary** [node-red/flow-library#9]
The following error appears to have killed the flow library. A quick restart and it was up and running again.

Recording it here as there's probably some error handling missing...

```
MongoError: topology was destroyed
    at Server.update (/home/knolleary/webapps/flows/flow-library/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:984:49)
    at Server.update (/home/knolleary/webapps/flows/flow-library/node_modules/connect-mongo/node_modules/mongodb/lib/server.js:332:17)
    at updateDocuments (/home/knolleary/webapps/flows/flow-library/node_modules/connect-mongo/node_modules/mongodb/lib/collection.js:980:19)
    at Collection.update (/home/knolleary/webapps/flows/flow-library/node_modules/connect-mongo/node_modules/mongodb/lib/collection.js:1018:44)
    at /home/knolleary/webapps/flows/flow-library/node_modules/connect-mongo/lib/connect-mongo.js:340:18
    at MongoStore.getCollection (/home/knolleary/webapps/flows/flow-library/node_modules/connect-mongo/lib/connect-mongo.js:210:11)
    at MongoStore.set (/home/knolleary/webapps/flows/flow-library/node_modules/connect-mongo/lib/connect-mongo.js:338:10)
    at Session.save (/home/knolleary/webapps/flows/flow-library/node_modules/express/node_modules/connect/node_modules/express-session/session/session.js:71:25)
    at Session.save (/home/knolleary/webapps/flows/flow-library/node_modules/express/node_modules/connect/node_modules/express-session/index.js:327:15)
    at ServerResponse.end (/home/knolleary/webapps/flows/flow-library/node_modules/express/node_modules/connect/node_modules/express-session/index.js:285:21)
```

**Comment by knolleary** [comment]
Happened again today.

Based on some research, have set `saveUninitialized: false` of the express session - will see how that holds up.
